#include <iostream>
using namespace std;

int main() {
    cout << "Content-type:text/html\r\n\r\n";
    cout << "<!DOCTYPE html>\n";
    cout << "<html lang=\"en\">\n";
    cout << "<head>\n";
    cout << "<style>\n";
    cout << "* {\n";
    cout << "  box-sizing: border-box;\n";
    cout << "}\n";
    cout << "\n";
    cout << "body {\n";
    cout << "  font-family: verdana, sans-serif;\n";
    cout << "}\n";
    cout << "\n";
    cout << "/* Style the header */\n";
    cout << "header {\n";
    cout << "  background-color: #cc0000;\n";
    cout << "  padding: 30px;\n";
    cout << "  text-align: center;\n";
    cout << "  font-size: 35px;\n";
    cout << "  color: #ffcc00;\n";
    cout << "}\n";
    cout << "\n";
    cout << "/* Create two columns/boxes that floats next to each other */\n";
    cout << "nav {\n";
    cout << "  float: left;\n";
    cout << "  width: 30%;\n";
    cout << "  height: 300px; /* only for demonstration, should be removed */\n";
    cout << "  background: #cccccc;\n";
    cout << "  padding: 20px;\n";
    cout << "}\n";
    cout << "\n";
    cout << "/* Style the list inside the menu */\n";
    cout << "nav ul {\n";
    cout << "  list-style-type: none;\n";
    cout << "  padding: 0;\n";
    cout << "}\n";
    cout << "\n";
    cout << "article {\n";
    cout << "  float: left;\n";
    cout << "  padding: 20px;\n";
    cout << "  width: 70%;\n";
    cout << "  background-color: white;\n";
    cout << "  height: 300px; /* only for demonstration, should be removed */\n";
    cout << "}\n";
    cout << "\n";
    cout << "/* Clear floats after the columns */\n";
    cout << "section::after {\n";
    cout << "  content: \"\";\n";
    cout << "  display: table;\n";
    cout << "  clear: both;\n";
    cout << "}\n";
    cout << "\n";
    cout << "/* Style the footer */\n";
    cout << "footer {\n";
    cout << "  background-color: white;\n";
    cout << "  padding: 10px;\n";
    cout << "  text-align: center;\n";
    cout << "  color: #999999;\n";
    cout << "}\n";
    cout << "\n";
    cout << "/* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */\n";
    cout << "@media (max-width: 600px) {\n";
    cout << "  nav, article {\n";
    cout << "    width: 100%;\n";
    cout << "    height: auto;\n";
    cout << "  }\n";
    cout << "}\n";
    cout << "</style>\n";
    cout << "<title>Quake Syndrome</title>\n";
    cout << "</head>\n";
    cout << "<body>\n";
    cout << "<header>\n";
    cout << "<h1>Quake Syndrome</h1>\n";
    cout << "</header>\n";
    cout << "<section>\n";
    cout << "<nav>\n";
    cout << "<ul>\n";
    cout << "<li><a href=\"#\">Home</a></li>\n";
    cout << "</ul>\n";
    cout << "</nav>\n";
    cout << "<article>\n";
    cout << "<h2>Servers</h2>\n";
    cout << "<p>Table here</p>\n";
    cout << "</article>\n";
    cout << "</section>\n";
    cout << "<footer>\n";
    cout << "<p>Quake III</p>\n";
    cout << "</footer>\n";
    cout << "</body>\n";
    cout << "</html>\n";

    return 0;
}
