#include <iostream>
using namespace std;

int main() {
    cout << "Content-type:text/html\r\n\r\n";
    cout << "<!DOCTYPE html>\n";
    cout << "<html lang=\"en\">\n";
    cout << "<head>\n";
    cout << "<title>Quake Syndrome</title>\n";
    cout << "<style>\n";
    cout << "article\n";
    cout << "{\n";
    cout << "    padding:5px;\n";
    cout << "    margin-top:5px;\n";
    cout << "}\n";
    cout << "\n";
    cout << "header\n";
    cout << "{\n";
    cout << "    padding:0px;\n";
    cout << "    text-align:center;\n";
    cout << "}\n";
    cout << "\n";
    cout << "section\n";
    cout << "{\n";
    cout << "    padding:5px;\n";
    cout << "    margin-top:5px;\n";
    cout << "}\n";
    cout << "\n";
    cout << "footer\n";
    cout << "{\n";
    cout << "    padding:5px;\n";
    cout << "    text-align:center;\n";
    cout << "    color:#cccccc\n";
    cout << "}\n";
    cout << "\n";
    cout << "nav\n";
    cout << "{\n";
    cout << "    text-align:center;\n";
    cout << "}\n";
    cout << "ul li\n";
    cout << "{\n";
    cout << "    display:inline;\n";
    cout << "    padding-left:5px;\n";
    cout << "    padding-right:5px;\n";
    cout << "    text-align:left;\n";
    cout << "    font-size:16px;\n";
    cout << "}\n";
    cout << "</style>\n";
    cout << "</head>\n";
    cout << "<body>\n";
    cout << "<header>\n";
    cout << "<h1>Quake Syndrome</h1>\n";
    cout << "</header>\n";
    cout << "<section>\n";
    cout << "<nav>\n";
    cout << "<ul>\n";
    cout << "<li><a href=\"#\">Home</a></li>\n";
    cout << "</ul>\n";
    cout << "</nav>\n";
    cout << "<article>\n";
    cout << "<h2>Servers</h2>\n";
    cout << "<p>Table here</p>\n";
    cout << "</article>\n";
    cout << "</section>\n";
    cout << "<footer>\n";
    cout << "<p>Quake III</p>\n";
    cout << "</footer>\n";
    cout << "</body>\n";
    cout << "</html>\n";

    return 0;
}
